name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build \helloDocker\app\dockerConsole.csproj -c Release
    - name: Publish with dotnet
      run: dotnet publish \helloDocker\app\dockerConsole.csproj -c Release
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . -f \helloDocker\Dockerfile -t my-image-name:$(date +%s)
