name: Docker Image CI for helloDocker project

on:
  push:
    branches: 
      - master
    paths:
      - 'helloDocker/*'

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 3.0.100
      
    - name: Build with dotnet
      run: dotnet build ${GITHUB_WORKSPACE}/helloDocker/app/dockerConsole.csproj -c Release
    - name: Publish with dotnet
      run: dotnet publish ${GITHUB_WORKSPACE}/helloDocker/app/dockerConsole.csproj -c Release
    - name: Build the Docker image
      run: docker build -f ${GITHUB_WORKSPACE}/helloDocker/Dockerfile -t my-image-name:$(date +%s) .
