name: CI for launchDarkly 

on:
  push:
    branches: 
      - master
    paths:
      - 'src/launchDarkly/*'

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 3.0.100  
    - name: Build with dotnet
      run: dotnet build ${GITHUB_WORKSPACE}/src/launchDarkly/launchDarkly.csproj -c Release -o output/launchDarkly/build
    - name: Publish with dotnet
      run: dotnet publish ${GITHUB_WORKSPACE}/src/launchDarkly/launchDarkly.csproj -c Release -o output/launchDarkly/publish
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: output
