
name: Build Akris Console

on:
  pull_request:
    branches: 
    - sprint/*
    - master
    paths: 'Akris-Console/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10','12']

    name: Node ${{ matrix.node }} sample
    env:
        Akris.Console.Dir_path: ${{github.workspace}}/Akris-Console/
        Akris.Console.Dir_PATH: ${{github.workspace}}/Akris-Console/
        Akris.Console.Dir1: ${{github.workspace}}
    #name: self hosted sample
    steps:
    - name: Configure Variables
      if: startsWith(github.base_ref, 'sprint/')
      run: |
        echo ${Akris.Console.Dir1}
        echo ${Akris.Console.Dir_path}
        echo ${Akris.Console.Dir_PATH}
        echo "this is sprint branch"
        echo ${{github.ref}}
        echo ${{github.head_ref}}
        echo ${{github.base_ref}}
        echo ${{github.event_name}}
        echo ${{github.actor}}
        echo ${{github.repository}}
        echo ${{github.event}}
        echo ${{github.event_path}}
        echo ${{github.workflow}}
        echo ${{github.workspace}}/Akris-Console/
    - name: Configure Variables
      if: startsWith(github.base_ref, 'master')
      run: |
        echo "this is master branch"
        echo ${{github.ref}}
        echo ${{github.head_ref}}
        echo ${{github.base_ref}}
        echo ${{github.event_name}}
        echo ${{github.actor}}
        echo ${{github.repository}}
        echo ${{github.event}}
        echo ${{github.event_path}}
        echo ${{github.workflow}}
        echo ${{github.workspace}}/Akris-Console/
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1  
    - uses: actions/setup-node@v1
      with:
        #node-version: '12'
        node-version: ${{ matrix.node }}
